language: php
php:
  - '5.5'
  - '5.6'
install:
   - composer self-update
   - composer install --prefer-dist
before_script: chmod 444 tests/fixtures/invalid/perms/*/composer.json
script:
    - phpunit -c tests/phpunit.xml
after_script:
    - vendor/bin/coveralls -v
