#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('RELEASE_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('RELEASE_COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );

    die(1);
}

require RELEASE_COMPOSER_INSTALL;

use Release\Command\Bump;
use Release\Command\Current;
use Symfony\Component\Console\Application;

$command = new Current();
$application = new Application();
$application->add(new Bump());
$application->add($command);
$application->setDefaultCommand($command->getName());
$application->run();
