#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Release\Command\Current;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Current());
$application->run();
